repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: go-fmt
        name: go fmt
        entry: gofmt -w
        language: system
        types: [go]
        pass_filenames: true

      - id: go-vet
        name: go vet
        entry: go vet ./...
        language: system
        types: [go]
        require_serial: true
        pass_filenames: false

      - id: golangci-lint
        name: golangci-lint
        entry: golangci-lint run --timeout=5m
        language: system
        types: [go]
        require_serial: true
        pass_filenames: false
