---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: btrfs-secondary
provisioner: btrfs.csi.local
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
allowVolumeExpansion: true
parameters:
  pool: secondary
