---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: btrfs-nodatacow
provisioner: btrfs.csi.local
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
allowVolumeExpansion: true
parameters:
  cow: "false"
