---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  # Patch all kubelet paths from /var/lib/kubelet to /var/lib/k0s/kubelet.
  - target:
      kind: DaemonSet
      name: btrfs-csi-driver
    patch: |
      - op: replace
        path: /spec/template/spec/volumes/0/hostPath/path
        value: /var/lib/k0s/kubelet/plugins/btrfs.csi.local
      - op: replace
        path: /spec/template/spec/volumes/1/hostPath/path
        value: /var/lib/k0s/kubelet/plugins_registry
      - op: replace
        path: /spec/template/spec/volumes/2/hostPath/path
        value: /var/lib/k0s/kubelet/pods
      - op: replace
        path: /spec/template/spec/containers/0/volumeMounts/1/mountPath
        value: /var/lib/k0s/kubelet/pods
      - op: replace
        path: /spec/template/spec/containers/2/args/1
        value: --kubelet-registration-path=/var/lib/k0s/kubelet/plugins/btrfs.csi.local/csi.sock
