---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../components/labels
resources:
  - namespace.yaml
  - csi-driver.yaml
  - rbac.yaml
  - plugin.yaml
images:
  - name: ghcr.io/mporrato/btrfs-csi-driver
    newTag: stable
