---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: btrfs
provisioner: btrfs.csi.local
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
allowVolumeExpansion: true
# parameters:
#   pool: default  # optional; falls back to "default" or sole pool
