apiVersion: v1
kind: ConfigMap
metadata:
  name: btrfs-csi-basepaths
  namespace: btrfs-csi
data:
  # List one btrfs base path per line. All paths must be on btrfs filesystems.
  # Each path may be used as a StorageClass parameters.basePath value.
  # With a single pool, StorageClass need not specify basePath.
  # With multiple pools, each StorageClass must specify basePath explicitly.
  basepaths.txt: |
    /var/lib/btrfs-csi
